### ISSUE TITLE
OverflowError in Processing

### ISSUE THREAD

**Issue by TylerStokes10** [nugraph/nugraph#83]
I am trying to process a set of 1million events and I am obtaining this error: 

Traceback (most recent call last):
  File "/home/stokes/NUGRAPH_PDK_BranchTag/scripts/process.py", line 35, in <module>
    process(args)
  File "/home/stokes/NUGRAPH_PDK_BranchTag/scripts/process.py", line 31, in process
    f.process(processor, out)
  File "/home/stokes/mambaforge/envs/numl/lib/python3.11/site-packages/pynuml/io/file.py", line 793, in process
    self.read_data_all()
  File "/home/stokes/mambaforge/envs/numl/lib/python3.11/site-packages/pynuml/io/file.py", line 612, in read_data_all
    lower, upper = self.calc_bound_seq_cnt(group)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stokes/mambaforge/envs/numl/lib/python3.11/site-packages/pynuml/io/file.py", line 516, in calc_bound_seq_cnt
    comm.Scatterv([all_seq_cnt, count, displ, MPI.LONG_LONG], self._seq_cnt[group], root=0)
  File "mpi4py/MPI/Comm.pyx", line 758, in mpi4py.MPI.Comm.Scatterv
  File "mpi4py/MPI/msgbuffer.pxi", line 597, in mpi4py.MPI._p_msg_cco.for_scatter
  File "mpi4py/MPI/msgbuffer.pxi", line 499, in mpi4py.MPI._p_msg_cco.for_cco_send
  File "mpi4py/MPI/msgbuffer.pxi", line 353, in mpi4py.MPI.message_vector
  File "mpi4py/MPI/asarray.pxi", line 22, in mpi4py.MPI.chkarray
  File "mpi4py/MPI/asarray.pxi", line 15, in mpi4py.MPI.getarray
OverflowError: value too large to convert to int
Traceback (most recent call last):
  File "/home/stokes/NUGRAPH_PDK_BranchTag/scripts/process.py", line 35, in <module>
    process(args)
  File "/home/stokes/NUGRAPH_PDK_BranchTag/scripts/process.py", line 31, in process
    f.process(processor, out)
  File "/home/stokes/mambaforge/envs/numl/lib/python3.11/site-packages/pynuml/io/file.py", line 793, in process
    self.read_data_all()
  File "/home/stokes/mambaforge/envs/numl/lib/python3.11/site-packages/pynuml/io/file.py", line 612, in read_data_all
    lower, upper = self.calc_bound_seq_cnt(group)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stokes/mambaforge/envs/numl/lib/python3.11/site-packages/pynuml/io/file.py", line 516, in calc_bound_seq_cnt
    comm.Scatterv([all_seq_cnt, count, displ, MPI.LONG_LONG], self._seq_cnt[group], root=0)
  File "mpi4py/MPI/Comm.pyx", line 758, in mpi4py.MPI.Comm.Scatterv
  File "mpi4py/MPI/msgbuffer.pxi", line 606, in mpi4py.MPI._p_msg_cco.for_scatter
  File "mpi4py/MPI/msgbuffer.pxi", line 511, in mpi4py.MPI._p_msg_cco.for_cco_recv
  File "mpi4py/MPI/msgbuffer.pxi", line 250, in mpi4py.MPI.message_simple
  File "mpi4py/MPI/msgbuffer.pxi", line 50, in mpi4py.MPI.downcast
OverflowError: integer 4171183850 does not fit in 'int'

Is there a way to correct this?

**Comment by wkliao** [comment]
Can you run the following command, which shows the number of unique event IDs?
```
h5ls -r inputfile | grep event_id.seq_cnt
```

**Comment by TylerStokes10** [comment]
These are the 3 files that I have that are causing the error.  (600K events, 800K events, 1 mil events)  So I have ran the command for all 3 datasets:  

 h5ls -r PDK_300K_Atm_300K.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {1258550542/Inf, 2}
/event_table/event_id.seq_cnt Dataset {600000/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {506670513/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {258845869/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {179941487/Inf, 2}

(numl) [stokes@pg07 Process_PH5_Merge_Input]$ h5ls -r PDK_400K_Atm_400K.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {1668454112/Inf, 2}
/event_table/event_id.seq_cnt Dataset {799800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {674582979/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {341682802/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {239432229/Inf, 2}

(numl) [stokes@pg07 Process_PH5_Merge_Input]$ h5ls -r PDK_500K_Atm_500K.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {2085778862/Inf, 2}
/event_table/event_id.seq_cnt Dataset {999800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {843152435/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {427283283/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {299169838/Inf, 2}

**Comment by wkliao** [comment]
This is strange.
The size of `/event_table`'s `event_id.seq_cnt` should be the maximum among all tables.
FYI. the size of `event_id.seq_cnt` is the number of unique event IDs in a table.

I wonder how these input files were generated?

**Comment by TylerStokes10** [comment]
I am confused why the /event_tables should be the maximum here.  Each event would contain numerous hits and particles, so those would be greater than the number of events, no?  These files were generated using this: https://github.com/TylerStokes10/numl_tpc/tree/master/numl/NeutrinoML , which sholud be the same as the standard numl now: https://github.com/nugraph/numl

**Comment by wkliao** [comment]
Dataset `event_table/event_id` contains the event IDs, not the IDs of objects in individual events.
The event IDs is a tuple, for example `(run, subrun, evt)` and in your case, it is a 2-tuple, because
it is a 2D array of size 600000x2.

**Comment by TylerStokes10** [comment]
So there is something wrong with my files?  I followed the standard protocol for producing the files.

**Comment by TylerStokes10** [comment]
Ok, so I have 5 100K proton decay files, and numerous atmospheric neutrino files.  When I run the command over the files individually I get: (numl) [stokes@pg07 GNN_Samples_PDK]$ h5ls -r hA_LFG_GNN_Samples_100K_5.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {99996/Inf, 2}
/event_table/event_id.seq_cnt Dataset {100000/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {99996/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {99996/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {99830/Inf, 2}

 h5ls -r Atm_200Kv2.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {194226/Inf, 2}
/event_table/event_id.seq_cnt Dataset {199800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {194226/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {194226/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {179003/Inf, 2}

**Comment by wkliao** [comment]
Please let me know the command lines used in your runs of `ph5_concat` and `add_key`.

**Comment by TylerStokes10** [comment]
This is the ph5_concat command: ph5_concat -o test_for_error.h5 -i file_list.txt

When I run the h5ls command I get:
 h5ls -r test_for_error.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {734652465/Inf, 2}
/event_table/event_id.seq_cnt Dataset {299800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {285485373/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {155674874/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {104593948/Inf, 2}

**Comment by TylerStokes10** [comment]
It appears something has gone wrong with my ph5_concat command.

**Comment by wkliao** [comment]
That `h5ls` output indicates `event_id.seq_cnt ` already existed in those
2 input files before running `ph5_concat`.

Can you run command below to re-generate `event_id.seq_cnt`?
```
add_key -c -f -k event_table/event_id test_for_error.h5
```
Then, run `h5ls` command again and let me know the output.

**Comment by TylerStokes10** [comment]
I ran: 
add_key -c -f -r detector_table -k event_table/event_id test_for_error.h5

Followed by:
 h5ls -r test_for_error.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {294222/Inf, 2}
/event_table/event_id.seq_cnt Dataset {299800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {294222/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {294222/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {278833/Inf, 2}

**Comment by wkliao** [comment]
This appears to be correct, i.e. the size of `/event_table/event_id.seq_cnt`
is the maximum among all tables.

Now please run the same `add_key` command to re-generate
`event_id.seq_cnt ` for the 3 large files.

After that verify with `h5ls` command which should show the correct
sizes of `/event_table/event_id.seq_cnt`

**Comment by wkliao** [comment]
Let me know if re-running `add_key` reduced the size of `event_id.seq_cnt`
for all tables, except for `event_table`.

If it did not, then `add_key` must have bugs.

**Comment by TylerStokes10** [comment]
It worked!  I get the following now: 

h5ls -r PDK_300K_Atm_300K.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {391661/Inf, 2}
/event_table/event_id.seq_cnt Dataset {400000/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {391661/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {391661/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {368544/Inf, 2}

h5ls -r PDK_400K_Atm_400K.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {488721/Inf, 2}
/event_table/event_id.seq_cnt Dataset {499800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {488721/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {488721/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {457994/Inf, 2}

h5ls -r PDK_500K_Atm_500K.h5 | grep event_id.seq_cnt
/edep_table/event_id.seq_cnt Dataset {585887/Inf, 2}
/event_table/event_id.seq_cnt Dataset {599800/Inf, 2}
/hit_table/event_id.seq_cnt Dataset {585887/Inf, 2}
/particle_table/event_id.seq_cnt Dataset {585887/Inf, 2}
/spacepoint_table/event_id.seq_cnt Dataset {547547/Inf, 2}

**Comment by wkliao** [comment]
Great! Let me know if you encounter problems when running pynuml with
those new files.

**Comment by TylerStokes10** [comment]
So I do encounter other issues on some events within the files.  I believe these issues are tied to panda in the standard.py labelling scheme.  Would you like me to share them here?

**Comment by wkliao** [comment]
If it is not related to this issue, then the best is to create a new issue.

**Comment by vhewes** [comment]
looks like this was resolved, so marking this issue complete. thank you @wkliao!!
